name: Nextflow website build
# read more here
# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Nextflow website build
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      fail-fast: false

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish website
        run: |
          make build
          make publish
          make invalidate
        env:
          AWS_EC2_METADATA_DISABLED: true
          AWS_ACCESS_KEY_ID: ${{secrets.NXF_AWS_ACCESS}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.NXF_AWS_SECRET}}
